- name: Install magento2 in LAMP
  hosts: servers
  become: true
  pre_tasks:
    - name: install pymysql 2.7 3.0
      apt:
        name: "{{item}}"
        state: latest
      loop:
        - python3-pymysql
  roles:
#    - nginx
#    - php
#    - maria
#    - composer
    - magento