- name: Install Mariadb
  hosts: 192.168.224.128
  become: true
  become_user: root
  become_method: sudo
  vars_files:
    - variables.yml
  tasks:
    - name: install pip3
      apt: name=python3-pip state=present
    - name: Make sure pymysql is present
      pip:
        name: pymysql
        state: present
    - name: update cache
      apt: update_cache=yes
    - name: install mariadb
      apt:
        name: mariadb-server
        state: latest
    - name: Create database user with password and all database privileges and 'WITH GRANT OPTION'
      community.mysql.mysql_user:
        name: "{{mysql_user}}"
        login_unix_socket: /var/run/mysqld/mysqld.sock
        check_implicit_admin: true
        password: "{{mysql_password}}"
        priv: '*.*:ALL,GRANT'
        state: present
    - name: Create a new database
      community.mysql.mysql_db:
        login_user: "{{mysql_user}}"
        login_password: "{{mysql_password}}"
        name: "{{db_name}}"
        state: present
