- name: config webserver
  hosts: servers
  become: true
  become_user: root
  become_method: sudo
  vars_files:
    - variables.yml
  tasks:
    - name: install nginx
      apt: name=nginx state=latest
    - name: start nginx
      service: name=nginx state=restarted
