- name: config php
  hosts: 192.168.224.128
  become: true
  become_user: root
  become_method: sudo
  vars_files:
    - variables.yml
  tasks:
    - name: install spc
      apt: name=software-properties-common
    - name: add repository ppa
      apt_repository: repo='ppa:ondrej/php'
    - name: install php
      apt:
        name: "{{php_pks}}"
    - name: php.ini
        replace:
          path: "/etc/php/7.4/fpm/php.ini"
          regexp: "^memory_limit = .+$"
          line: 'short_open_tag = On'
          backup: yes
